/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendadecontatos;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author aluno
 */
public class TelaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel6 = new javax.swing.JLabel();
        lblSO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuContatos = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuTrocarUsuario = new javax.swing.JMenu();
        mnuMudarSenha = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuSom = new javax.swing.JCheckBoxMenuItem();
        mnuTemas = new javax.swing.JMenu();
        mnuNimbus = new javax.swing.JCheckBoxMenuItem();
        mnuGTK = new javax.swing.JCheckBoxMenuItem();
        mnuMacOSX = new javax.swing.JCheckBoxMenuItem();
        mnuAluminium = new javax.swing.JCheckBoxMenuItem();
        mnuWindows = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno\\Pictures\\aula_2016_09_09\\agenda.png")); // NOI18N

        jToolBar1.setRollover(true);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno\\Pictures\\aula_2016_09_09\\0198.png")); // NOI18N
        jLabel2.setText("Usuário: ");
        jToolBar1.add(jLabel2);

        lblUsuario.setMaximumSize(new java.awt.Dimension(200, 16));
        lblUsuario.setMinimumSize(new java.awt.Dimension(200, 16));
        jToolBar1.add(lblUsuario);
        jToolBar1.add(jSeparator2);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno\\Pictures\\aula_2016_09_09\\0277.png")); // NOI18N
        jLabel4.setText("Nível: ");
        jToolBar1.add(jLabel4);

        lblNivel.setMaximumSize(new java.awt.Dimension(200, 16));
        lblNivel.setMinimumSize(new java.awt.Dimension(200, 16));
        jToolBar1.add(lblNivel);
        jToolBar1.add(jSeparator3);

        jLabel6.setText("S.O.:");
        jToolBar1.add(jLabel6);

        lblSO.setMaximumSize(new java.awt.Dimension(200, 16));
        lblSO.setMinimumSize(new java.awt.Dimension(200, 16));
        jToolBar1.add(lblSO);

        jMenu1.setText("Cadastros");

        mnuContatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0189.png"))); // NOI18N
        mnuContatos.setText("Contatos");
        mnuContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContatosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuContatos);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno\\Pictures\\aula_2016_09_09\\0198.png")); // NOI18N
        mnuUsuarios.setText("Usuários");

        mnuTrocarUsuario.setText("Trocar Usuário");
        mnuUsuarios.add(mnuTrocarUsuario);

        mnuMudarSenha.setText("Mudar Senha");
        mnuUsuarios.add(mnuMudarSenha);

        jMenu1.add(mnuUsuarios);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno\\Pictures\\aula_2016_09_09\\0190.png")); // NOI18N
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configurações");

        mnuSom.setSelected(true);
        mnuSom.setText("Som");
        mnuSom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSomActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSom);

        mnuTemas.setText("Temas");

        buttonGroup1.add(mnuNimbus);
        mnuNimbus.setSelected(true);
        mnuNimbus.setText("Nimbus");
        mnuNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNimbusActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuNimbus);

        buttonGroup1.add(mnuGTK);
        mnuGTK.setText("GTK+");
        mnuGTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGTKActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuGTK);

        buttonGroup1.add(mnuMacOSX);
        mnuMacOSX.setText("Mac OS X");
        mnuMacOSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMacOSXActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuMacOSX);

        buttonGroup1.add(mnuAluminium);
        mnuAluminium.setText("Aluminium");
        mnuAluminium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAluminiumActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuAluminium);

        buttonGroup1.add(mnuWindows);
        mnuWindows.setText("Windows");
        mnuWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsActionPerformed(evt);
            }
        });
        mnuTemas.add(mnuWindows);

        jMenu2.add(mnuTemas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(790, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuContatosActionPerformed

    private void mnuSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSomActionPerformed

    private void mnuNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNimbusActionPerformed
 mudaLaF("javax.swing.plaf.nimbus.NimbusLookAndFeel");
    }//GEN-LAST:event_mnuNimbusActionPerformed

    private void mnuGTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGTKActionPerformed
 mudaLaF("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
    }//GEN-LAST:event_mnuGTKActionPerformed

    private void mnuMacOSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMacOSXActionPerformed
mudaLaF("com.apple.laf.AquaLookAndFeel");
    }//GEN-LAST:event_mnuMacOSXActionPerformed

    private void mnuAluminiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAluminiumActionPerformed
mudaLaF("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
    }//GEN-LAST:event_mnuAluminiumActionPerformed

    private void mnuWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWindowsActionPerformed
mudaLaF("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    }//GEN-LAST:event_mnuWindowsActionPerformed
//private void mnuTrocaUsuarioActionPerformed(java.awt.ActiveEvent){
  //  TelaLogin
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }
    
    private void mudaLaF(String temaLaF){
        try{
            UIManager.setLookAndFeel(temaLaF);
            SwingUtilities.updateComponentTreeUI(this);
            
        }catch(ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex){
            JOptionPane.showMessageDialog(null, "Tema não suportado neste S.O.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSO;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JCheckBoxMenuItem mnuAluminium;
    private javax.swing.JMenuItem mnuContatos;
    private javax.swing.JCheckBoxMenuItem mnuGTK;
    private javax.swing.JCheckBoxMenuItem mnuMacOSX;
    private javax.swing.JMenu mnuMudarSenha;
    private javax.swing.JCheckBoxMenuItem mnuNimbus;
    private javax.swing.JCheckBoxMenuItem mnuSom;
    private javax.swing.JMenu mnuTemas;
    private javax.swing.JMenu mnuTrocarUsuario;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JCheckBoxMenuItem mnuWindows;
    // End of variables declaration//GEN-END:variables
}
